# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cefour/Projects/pmq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cefour/Projects/pmq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cpack" --config ./CPackSourceConfig.cmake /Users/cefour/Projects/pmq/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	"/Users/cefour/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/193.5233.103/CLion.app/Contents/bin/cmake/mac/bin/cpack" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cefour/Projects/pmq/CMakeFiles /Users/cefour/Projects/pmq/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cefour/Projects/pmq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

#=============================================================================
# Target rules for targets named test_utf8

# Build rule for target.
test_utf8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_utf8
.PHONY : test_utf8

# fast build rule for target.
test_utf8/fast:
	$(MAKE) -f CMakeFiles/test_utf8.dir/build.make CMakeFiles/test_utf8.dir/build
.PHONY : test_utf8/fast

#=============================================================================
# Target rules for targets named test_login_handler

# Build rule for target.
test_login_handler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_login_handler
.PHONY : test_login_handler

# fast build rule for target.
test_login_handler/fast:
	$(MAKE) -f CMakeFiles/test_login_handler.dir/build.make CMakeFiles/test_login_handler.dir/build
.PHONY : test_login_handler/fast

#=============================================================================
# Target rules for targets named test_http_rest_server

# Build rule for target.
test_http_rest_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_rest_server
.PHONY : test_http_rest_server

# fast build rule for target.
test_http_rest_server/fast:
	$(MAKE) -f CMakeFiles/test_http_rest_server.dir/build.make CMakeFiles/test_http_rest_server.dir/build
.PHONY : test_http_rest_server/fast

#=============================================================================
# Target rules for targets named test_subscriber_container

# Build rule for target.
test_subscriber_container: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_subscriber_container
.PHONY : test_subscriber_container

# fast build rule for target.
test_subscriber_container/fast:
	$(MAKE) -f CMakeFiles/test_subscriber_container.dir/build.make CMakeFiles/test_subscriber_container.dir/build
.PHONY : test_subscriber_container/fast

#=============================================================================
# Target rules for targets named test_login_factory

# Build rule for target.
test_login_factory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_login_factory
.PHONY : test_login_factory

# fast build rule for target.
test_login_factory/fast:
	$(MAKE) -f CMakeFiles/test_login_factory.dir/build.make CMakeFiles/test_login_factory.dir/build
.PHONY : test_login_factory/fast

#=============================================================================
# Target rules for targets named pmqttclient

# Build rule for target.
pmqttclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pmqttclient
.PHONY : pmqttclient

# fast build rule for target.
pmqttclient/fast:
	$(MAKE) -f CMakeFiles/pmqttclient.dir/build.make CMakeFiles/pmqttclient.dir/build
.PHONY : pmqttclient/fast

#=============================================================================
# Target rules for targets named PMQ

# Build rule for target.
PMQ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PMQ
.PHONY : PMQ

# fast build rule for target.
PMQ/fast:
	$(MAKE) -f CMakeFiles/PMQ.dir/build.make CMakeFiles/PMQ.dir/build
.PHONY : PMQ/fast

#=============================================================================
# Target rules for targets named pmq_obj_lib

# Build rule for target.
pmq_obj_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pmq_obj_lib
.PHONY : pmq_obj_lib

# fast build rule for target.
pmq_obj_lib/fast:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/build
.PHONY : pmq_obj_lib/fast

#=============================================================================
# Target rules for targets named pmqtt

# Build rule for target.
pmqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pmqtt
.PHONY : pmqtt

# fast build rule for target.
pmqtt/fast:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/build
.PHONY : pmqtt/fast

client/messenger.o: client/messenger.cpp.o

.PHONY : client/messenger.o

# target to build an object file
client/messenger.cpp.o:
	$(MAKE) -f CMakeFiles/pmqttclient.dir/build.make CMakeFiles/pmqttclient.dir/client/messenger.cpp.o
.PHONY : client/messenger.cpp.o

client/messenger.i: client/messenger.cpp.i

.PHONY : client/messenger.i

# target to preprocess a source file
client/messenger.cpp.i:
	$(MAKE) -f CMakeFiles/pmqttclient.dir/build.make CMakeFiles/pmqttclient.dir/client/messenger.cpp.i
.PHONY : client/messenger.cpp.i

client/messenger.s: client/messenger.cpp.s

.PHONY : client/messenger.s

# target to generate assembly for a file
client/messenger.cpp.s:
	$(MAKE) -f CMakeFiles/pmqttclient.dir/build.make CMakeFiles/pmqttclient.dir/client/messenger.cpp.s
.PHONY : client/messenger.cpp.s

lib/container/subscriber.o: lib/container/subscriber.cpp.o

.PHONY : lib/container/subscriber.o

# target to build an object file
lib/container/subscriber.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/container/subscriber.cpp.o
.PHONY : lib/container/subscriber.cpp.o

lib/container/subscriber.i: lib/container/subscriber.cpp.i

.PHONY : lib/container/subscriber.i

# target to preprocess a source file
lib/container/subscriber.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/container/subscriber.cpp.i
.PHONY : lib/container/subscriber.cpp.i

lib/container/subscriber.s: lib/container/subscriber.cpp.s

.PHONY : lib/container/subscriber.s

# target to generate assembly for a file
lib/container/subscriber.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/container/subscriber.cpp.s
.PHONY : lib/container/subscriber.cpp.s

lib/container/subscriber_container.o: lib/container/subscriber_container.cpp.o

.PHONY : lib/container/subscriber_container.o

# target to build an object file
lib/container/subscriber_container.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_container.cpp.o
.PHONY : lib/container/subscriber_container.cpp.o

lib/container/subscriber_container.i: lib/container/subscriber_container.cpp.i

.PHONY : lib/container/subscriber_container.i

# target to preprocess a source file
lib/container/subscriber_container.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_container.cpp.i
.PHONY : lib/container/subscriber_container.cpp.i

lib/container/subscriber_container.s: lib/container/subscriber_container.cpp.s

.PHONY : lib/container/subscriber_container.s

# target to generate assembly for a file
lib/container/subscriber_container.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_container.cpp.s
.PHONY : lib/container/subscriber_container.cpp.s

lib/container/subscriber_node.o: lib/container/subscriber_node.cpp.o

.PHONY : lib/container/subscriber_node.o

# target to build an object file
lib/container/subscriber_node.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_node.cpp.o
.PHONY : lib/container/subscriber_node.cpp.o

lib/container/subscriber_node.i: lib/container/subscriber_node.cpp.i

.PHONY : lib/container/subscriber_node.i

# target to preprocess a source file
lib/container/subscriber_node.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_node.cpp.i
.PHONY : lib/container/subscriber_node.cpp.i

lib/container/subscriber_node.s: lib/container/subscriber_node.cpp.s

.PHONY : lib/container/subscriber_node.s

# target to generate assembly for a file
lib/container/subscriber_node.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/container/subscriber_node.cpp.s
.PHONY : lib/container/subscriber_node.cpp.s

lib/detail/string.o: lib/detail/string.cpp.o

.PHONY : lib/detail/string.o

# target to build an object file
lib/detail/string.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/detail/string.cpp.o
.PHONY : lib/detail/string.cpp.o

lib/detail/string.i: lib/detail/string.cpp.i

.PHONY : lib/detail/string.i

# target to preprocess a source file
lib/detail/string.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/detail/string.cpp.i
.PHONY : lib/detail/string.cpp.i

lib/detail/string.s: lib/detail/string.cpp.s

.PHONY : lib/detail/string.s

# target to generate assembly for a file
lib/detail/string.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/detail/string.cpp.s
.PHONY : lib/detail/string.cpp.s

lib/mqtt/message.o: lib/mqtt/message.cpp.o

.PHONY : lib/mqtt/message.o

# target to build an object file
lib/mqtt/message.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/message.cpp.o
.PHONY : lib/mqtt/message.cpp.o

lib/mqtt/message.i: lib/mqtt/message.cpp.i

.PHONY : lib/mqtt/message.i

# target to preprocess a source file
lib/mqtt/message.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/message.cpp.i
.PHONY : lib/mqtt/message.cpp.i

lib/mqtt/message.s: lib/mqtt/message.cpp.s

.PHONY : lib/mqtt/message.s

# target to generate assembly for a file
lib/mqtt/message.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/message.cpp.s
.PHONY : lib/mqtt/message.cpp.s

lib/mqtt/mqtt_connect.o: lib/mqtt/mqtt_connect.cpp.o

.PHONY : lib/mqtt/mqtt_connect.o

# target to build an object file
lib/mqtt/mqtt_connect.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_connect.cpp.o
.PHONY : lib/mqtt/mqtt_connect.cpp.o

lib/mqtt/mqtt_connect.i: lib/mqtt/mqtt_connect.cpp.i

.PHONY : lib/mqtt/mqtt_connect.i

# target to preprocess a source file
lib/mqtt/mqtt_connect.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_connect.cpp.i
.PHONY : lib/mqtt/mqtt_connect.cpp.i

lib/mqtt/mqtt_connect.s: lib/mqtt/mqtt_connect.cpp.s

.PHONY : lib/mqtt/mqtt_connect.s

# target to generate assembly for a file
lib/mqtt/mqtt_connect.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_connect.cpp.s
.PHONY : lib/mqtt/mqtt_connect.cpp.s

lib/mqtt/mqtt_message.o: lib/mqtt/mqtt_message.cpp.o

.PHONY : lib/mqtt/mqtt_message.o

# target to build an object file
lib/mqtt/mqtt_message.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message.cpp.o
.PHONY : lib/mqtt/mqtt_message.cpp.o

lib/mqtt/mqtt_message.i: lib/mqtt/mqtt_message.cpp.i

.PHONY : lib/mqtt/mqtt_message.i

# target to preprocess a source file
lib/mqtt/mqtt_message.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message.cpp.i
.PHONY : lib/mqtt/mqtt_message.cpp.i

lib/mqtt/mqtt_message.s: lib/mqtt/mqtt_message.cpp.s

.PHONY : lib/mqtt/mqtt_message.s

# target to generate assembly for a file
lib/mqtt/mqtt_message.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message.cpp.s
.PHONY : lib/mqtt/mqtt_message.cpp.s

lib/mqtt/mqtt_message_processor.o: lib/mqtt/mqtt_message_processor.cpp.o

.PHONY : lib/mqtt/mqtt_message_processor.o

# target to build an object file
lib/mqtt/mqtt_message_processor.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message_processor.cpp.o
.PHONY : lib/mqtt/mqtt_message_processor.cpp.o

lib/mqtt/mqtt_message_processor.i: lib/mqtt/mqtt_message_processor.cpp.i

.PHONY : lib/mqtt/mqtt_message_processor.i

# target to preprocess a source file
lib/mqtt/mqtt_message_processor.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message_processor.cpp.i
.PHONY : lib/mqtt/mqtt_message_processor.cpp.i

lib/mqtt/mqtt_message_processor.s: lib/mqtt/mqtt_message_processor.cpp.s

.PHONY : lib/mqtt/mqtt_message_processor.s

# target to generate assembly for a file
lib/mqtt/mqtt_message_processor.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_message_processor.cpp.s
.PHONY : lib/mqtt/mqtt_message_processor.cpp.s

lib/mqtt/mqtt_package.o: lib/mqtt/mqtt_package.cpp.o

.PHONY : lib/mqtt/mqtt_package.o

# target to build an object file
lib/mqtt/mqtt_package.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_package.cpp.o
.PHONY : lib/mqtt/mqtt_package.cpp.o

lib/mqtt/mqtt_package.i: lib/mqtt/mqtt_package.cpp.i

.PHONY : lib/mqtt/mqtt_package.i

# target to preprocess a source file
lib/mqtt/mqtt_package.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_package.cpp.i
.PHONY : lib/mqtt/mqtt_package.cpp.i

lib/mqtt/mqtt_package.s: lib/mqtt/mqtt_package.cpp.s

.PHONY : lib/mqtt/mqtt_package.s

# target to generate assembly for a file
lib/mqtt/mqtt_package.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_package.cpp.s
.PHONY : lib/mqtt/mqtt_package.cpp.s

lib/mqtt/mqtt_publish.o: lib/mqtt/mqtt_publish.cpp.o

.PHONY : lib/mqtt/mqtt_publish.o

# target to build an object file
lib/mqtt/mqtt_publish.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_publish.cpp.o
.PHONY : lib/mqtt/mqtt_publish.cpp.o

lib/mqtt/mqtt_publish.i: lib/mqtt/mqtt_publish.cpp.i

.PHONY : lib/mqtt/mqtt_publish.i

# target to preprocess a source file
lib/mqtt/mqtt_publish.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_publish.cpp.i
.PHONY : lib/mqtt/mqtt_publish.cpp.i

lib/mqtt/mqtt_publish.s: lib/mqtt/mqtt_publish.cpp.s

.PHONY : lib/mqtt/mqtt_publish.s

# target to generate assembly for a file
lib/mqtt/mqtt_publish.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_publish.cpp.s
.PHONY : lib/mqtt/mqtt_publish.cpp.s

lib/mqtt/mqtt_subscribe.o: lib/mqtt/mqtt_subscribe.cpp.o

.PHONY : lib/mqtt/mqtt_subscribe.o

# target to build an object file
lib/mqtt/mqtt_subscribe.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_subscribe.cpp.o
.PHONY : lib/mqtt/mqtt_subscribe.cpp.o

lib/mqtt/mqtt_subscribe.i: lib/mqtt/mqtt_subscribe.cpp.i

.PHONY : lib/mqtt/mqtt_subscribe.i

# target to preprocess a source file
lib/mqtt/mqtt_subscribe.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_subscribe.cpp.i
.PHONY : lib/mqtt/mqtt_subscribe.cpp.i

lib/mqtt/mqtt_subscribe.s: lib/mqtt/mqtt_subscribe.cpp.s

.PHONY : lib/mqtt/mqtt_subscribe.s

# target to generate assembly for a file
lib/mqtt/mqtt_subscribe.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_subscribe.cpp.s
.PHONY : lib/mqtt/mqtt_subscribe.cpp.s

lib/mqtt/mqtt_types.o: lib/mqtt/mqtt_types.cpp.o

.PHONY : lib/mqtt/mqtt_types.o

# target to build an object file
lib/mqtt/mqtt_types.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_types.cpp.o
.PHONY : lib/mqtt/mqtt_types.cpp.o

lib/mqtt/mqtt_types.i: lib/mqtt/mqtt_types.cpp.i

.PHONY : lib/mqtt/mqtt_types.i

# target to preprocess a source file
lib/mqtt/mqtt_types.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_types.cpp.i
.PHONY : lib/mqtt/mqtt_types.cpp.i

lib/mqtt/mqtt_types.s: lib/mqtt/mqtt_types.cpp.s

.PHONY : lib/mqtt/mqtt_types.s

# target to generate assembly for a file
lib/mqtt/mqtt_types.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/mqtt/mqtt_types.cpp.s
.PHONY : lib/mqtt/mqtt_types.cpp.s

lib/network/ssl_client_factory.o: lib/network/ssl_client_factory.cpp.o

.PHONY : lib/network/ssl_client_factory.o

# target to build an object file
lib/network/ssl_client_factory.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/ssl_client_factory.cpp.o
.PHONY : lib/network/ssl_client_factory.cpp.o

lib/network/ssl_client_factory.i: lib/network/ssl_client_factory.cpp.i

.PHONY : lib/network/ssl_client_factory.i

# target to preprocess a source file
lib/network/ssl_client_factory.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/ssl_client_factory.cpp.i
.PHONY : lib/network/ssl_client_factory.cpp.i

lib/network/ssl_client_factory.s: lib/network/ssl_client_factory.cpp.s

.PHONY : lib/network/ssl_client_factory.s

# target to generate assembly for a file
lib/network/ssl_client_factory.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/ssl_client_factory.cpp.s
.PHONY : lib/network/ssl_client_factory.cpp.s

lib/network/tcp_client_factory.o: lib/network/tcp_client_factory.cpp.o

.PHONY : lib/network/tcp_client_factory.o

# target to build an object file
lib/network/tcp_client_factory.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/tcp_client_factory.cpp.o
.PHONY : lib/network/tcp_client_factory.cpp.o

lib/network/tcp_client_factory.i: lib/network/tcp_client_factory.cpp.i

.PHONY : lib/network/tcp_client_factory.i

# target to preprocess a source file
lib/network/tcp_client_factory.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/tcp_client_factory.cpp.i
.PHONY : lib/network/tcp_client_factory.cpp.i

lib/network/tcp_client_factory.s: lib/network/tcp_client_factory.cpp.s

.PHONY : lib/network/tcp_client_factory.s

# target to generate assembly for a file
lib/network/tcp_client_factory.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/network/tcp_client_factory.cpp.s
.PHONY : lib/network/tcp_client_factory.cpp.s

lib/qos/qos_handler_factory.o: lib/qos/qos_handler_factory.cpp.o

.PHONY : lib/qos/qos_handler_factory.o

# target to build an object file
lib/qos/qos_handler_factory.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_handler_factory.cpp.o
.PHONY : lib/qos/qos_handler_factory.cpp.o

lib/qos/qos_handler_factory.i: lib/qos/qos_handler_factory.cpp.i

.PHONY : lib/qos/qos_handler_factory.i

# target to preprocess a source file
lib/qos/qos_handler_factory.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_handler_factory.cpp.i
.PHONY : lib/qos/qos_handler_factory.cpp.i

lib/qos/qos_handler_factory.s: lib/qos/qos_handler_factory.cpp.s

.PHONY : lib/qos/qos_handler_factory.s

# target to generate assembly for a file
lib/qos/qos_handler_factory.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_handler_factory.cpp.s
.PHONY : lib/qos/qos_handler_factory.cpp.s

lib/qos/qos_one_handler.o: lib/qos/qos_one_handler.cpp.o

.PHONY : lib/qos/qos_one_handler.o

# target to build an object file
lib/qos/qos_one_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_one_handler.cpp.o
.PHONY : lib/qos/qos_one_handler.cpp.o

lib/qos/qos_one_handler.i: lib/qos/qos_one_handler.cpp.i

.PHONY : lib/qos/qos_one_handler.i

# target to preprocess a source file
lib/qos/qos_one_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_one_handler.cpp.i
.PHONY : lib/qos/qos_one_handler.cpp.i

lib/qos/qos_one_handler.s: lib/qos/qos_one_handler.cpp.s

.PHONY : lib/qos/qos_one_handler.s

# target to generate assembly for a file
lib/qos/qos_one_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_one_handler.cpp.s
.PHONY : lib/qos/qos_one_handler.cpp.s

lib/qos/qos_two_handler.o: lib/qos/qos_two_handler.cpp.o

.PHONY : lib/qos/qos_two_handler.o

# target to build an object file
lib/qos/qos_two_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_two_handler.cpp.o
.PHONY : lib/qos/qos_two_handler.cpp.o

lib/qos/qos_two_handler.i: lib/qos/qos_two_handler.cpp.i

.PHONY : lib/qos/qos_two_handler.i

# target to preprocess a source file
lib/qos/qos_two_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_two_handler.cpp.i
.PHONY : lib/qos/qos_two_handler.cpp.i

lib/qos/qos_two_handler.s: lib/qos/qos_two_handler.cpp.s

.PHONY : lib/qos/qos_two_handler.s

# target to generate assembly for a file
lib/qos/qos_two_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_two_handler.cpp.s
.PHONY : lib/qos/qos_two_handler.cpp.s

lib/qos/qos_zero_handler.o: lib/qos/qos_zero_handler.cpp.o

.PHONY : lib/qos/qos_zero_handler.o

# target to build an object file
lib/qos/qos_zero_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_zero_handler.cpp.o
.PHONY : lib/qos/qos_zero_handler.cpp.o

lib/qos/qos_zero_handler.i: lib/qos/qos_zero_handler.cpp.i

.PHONY : lib/qos/qos_zero_handler.i

# target to preprocess a source file
lib/qos/qos_zero_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_zero_handler.cpp.i
.PHONY : lib/qos/qos_zero_handler.cpp.i

lib/qos/qos_zero_handler.s: lib/qos/qos_zero_handler.cpp.s

.PHONY : lib/qos/qos_zero_handler.s

# target to generate assembly for a file
lib/qos/qos_zero_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmqtt.dir/build.make CMakeFiles/pmqtt.dir/lib/qos/qos_zero_handler.cpp.s
.PHONY : lib/qos/qos_zero_handler.cpp.s

lib/rest/http_rest_server.o: lib/rest/http_rest_server.cpp.o

.PHONY : lib/rest/http_rest_server.o

# target to build an object file
lib/rest/http_rest_server.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/http_rest_server.cpp.o
.PHONY : lib/rest/http_rest_server.cpp.o

lib/rest/http_rest_server.i: lib/rest/http_rest_server.cpp.i

.PHONY : lib/rest/http_rest_server.i

# target to preprocess a source file
lib/rest/http_rest_server.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/http_rest_server.cpp.i
.PHONY : lib/rest/http_rest_server.cpp.i

lib/rest/http_rest_server.s: lib/rest/http_rest_server.cpp.s

.PHONY : lib/rest/http_rest_server.s

# target to generate assembly for a file
lib/rest/http_rest_server.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/http_rest_server.cpp.s
.PHONY : lib/rest/http_rest_server.cpp.s

lib/rest/route_handler.o: lib/rest/route_handler.cpp.o

.PHONY : lib/rest/route_handler.o

# target to build an object file
lib/rest/route_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/route_handler.cpp.o
.PHONY : lib/rest/route_handler.cpp.o

lib/rest/route_handler.i: lib/rest/route_handler.cpp.i

.PHONY : lib/rest/route_handler.i

# target to preprocess a source file
lib/rest/route_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/route_handler.cpp.i
.PHONY : lib/rest/route_handler.cpp.i

lib/rest/route_handler.s: lib/rest/route_handler.cpp.s

.PHONY : lib/rest/route_handler.s

# target to generate assembly for a file
lib/rest/route_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/rest/route_handler.cpp.s
.PHONY : lib/rest/route_handler.cpp.s

lib/server/client_handler.o: lib/server/client_handler.cpp.o

.PHONY : lib/server/client_handler.o

# target to build an object file
lib/server/client_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/client_handler.cpp.o
.PHONY : lib/server/client_handler.cpp.o

lib/server/client_handler.i: lib/server/client_handler.cpp.i

.PHONY : lib/server/client_handler.i

# target to preprocess a source file
lib/server/client_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/client_handler.cpp.i
.PHONY : lib/server/client_handler.cpp.i

lib/server/client_handler.s: lib/server/client_handler.cpp.s

.PHONY : lib/server/client_handler.s

# target to generate assembly for a file
lib/server/client_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/client_handler.cpp.s
.PHONY : lib/server/client_handler.cpp.s

lib/server/login/login_allow_anonymous_handler.o: lib/server/login/login_allow_anonymous_handler.cpp.o

.PHONY : lib/server/login/login_allow_anonymous_handler.o

# target to build an object file
lib/server/login/login_allow_anonymous_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_allow_anonymous_handler.cpp.o
.PHONY : lib/server/login/login_allow_anonymous_handler.cpp.o

lib/server/login/login_allow_anonymous_handler.i: lib/server/login/login_allow_anonymous_handler.cpp.i

.PHONY : lib/server/login/login_allow_anonymous_handler.i

# target to preprocess a source file
lib/server/login/login_allow_anonymous_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_allow_anonymous_handler.cpp.i
.PHONY : lib/server/login/login_allow_anonymous_handler.cpp.i

lib/server/login/login_allow_anonymous_handler.s: lib/server/login/login_allow_anonymous_handler.cpp.s

.PHONY : lib/server/login/login_allow_anonymous_handler.s

# target to generate assembly for a file
lib/server/login/login_allow_anonymous_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_allow_anonymous_handler.cpp.s
.PHONY : lib/server/login/login_allow_anonymous_handler.cpp.s

lib/server/login/login_factory.o: lib/server/login/login_factory.cpp.o

.PHONY : lib/server/login/login_factory.o

# target to build an object file
lib/server/login/login_factory.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_factory.cpp.o
.PHONY : lib/server/login/login_factory.cpp.o

lib/server/login/login_factory.i: lib/server/login/login_factory.cpp.i

.PHONY : lib/server/login/login_factory.i

# target to preprocess a source file
lib/server/login/login_factory.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_factory.cpp.i
.PHONY : lib/server/login/login_factory.cpp.i

lib/server/login/login_factory.s: lib/server/login/login_factory.cpp.s

.PHONY : lib/server/login/login_factory.s

# target to generate assembly for a file
lib/server/login/login_factory.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_factory.cpp.s
.PHONY : lib/server/login/login_factory.cpp.s

lib/server/login/login_handler.o: lib/server/login/login_handler.cpp.o

.PHONY : lib/server/login/login_handler.o

# target to build an object file
lib/server/login/login_handler.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_handler.cpp.o
.PHONY : lib/server/login/login_handler.cpp.o

lib/server/login/login_handler.i: lib/server/login/login_handler.cpp.i

.PHONY : lib/server/login/login_handler.i

# target to preprocess a source file
lib/server/login/login_handler.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_handler.cpp.i
.PHONY : lib/server/login/login_handler.cpp.i

lib/server/login/login_handler.s: lib/server/login/login_handler.cpp.s

.PHONY : lib/server/login/login_handler.s

# target to generate assembly for a file
lib/server/login/login_handler.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/login/login_handler.cpp.s
.PHONY : lib/server/login/login_handler.cpp.s

lib/server/server.o: lib/server/server.cpp.o

.PHONY : lib/server/server.o

# target to build an object file
lib/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/server.cpp.o
.PHONY : lib/server/server.cpp.o

lib/server/server.i: lib/server/server.cpp.i

.PHONY : lib/server/server.i

# target to preprocess a source file
lib/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/server.cpp.i
.PHONY : lib/server/server.cpp.i

lib/server/server.s: lib/server/server.cpp.s

.PHONY : lib/server/server.s

# target to generate assembly for a file
lib/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/server.cpp.s
.PHONY : lib/server/server.cpp.s

lib/server/startup_configuration.o: lib/server/startup_configuration.cpp.o

.PHONY : lib/server/startup_configuration.o

# target to build an object file
lib/server/startup_configuration.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/startup_configuration.cpp.o
.PHONY : lib/server/startup_configuration.cpp.o

lib/server/startup_configuration.i: lib/server/startup_configuration.cpp.i

.PHONY : lib/server/startup_configuration.i

# target to preprocess a source file
lib/server/startup_configuration.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/startup_configuration.cpp.i
.PHONY : lib/server/startup_configuration.cpp.i

lib/server/startup_configuration.s: lib/server/startup_configuration.cpp.s

.PHONY : lib/server/startup_configuration.s

# target to generate assembly for a file
lib/server/startup_configuration.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/server/startup_configuration.cpp.s
.PHONY : lib/server/startup_configuration.cpp.s

lib/storage/in_memory_storage.o: lib/storage/in_memory_storage.cpp.o

.PHONY : lib/storage/in_memory_storage.o

# target to build an object file
lib/storage/in_memory_storage.cpp.o:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/storage/in_memory_storage.cpp.o
.PHONY : lib/storage/in_memory_storage.cpp.o

lib/storage/in_memory_storage.i: lib/storage/in_memory_storage.cpp.i

.PHONY : lib/storage/in_memory_storage.i

# target to preprocess a source file
lib/storage/in_memory_storage.cpp.i:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/storage/in_memory_storage.cpp.i
.PHONY : lib/storage/in_memory_storage.cpp.i

lib/storage/in_memory_storage.s: lib/storage/in_memory_storage.cpp.s

.PHONY : lib/storage/in_memory_storage.s

# target to generate assembly for a file
lib/storage/in_memory_storage.cpp.s:
	$(MAKE) -f CMakeFiles/pmq_obj_lib.dir/build.make CMakeFiles/pmq_obj_lib.dir/lib/storage/in_memory_storage.cpp.s
.PHONY : lib/storage/in_memory_storage.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PMQ.dir/build.make CMakeFiles/PMQ.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PMQ.dir/build.make CMakeFiles/PMQ.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PMQ.dir/build.make CMakeFiles/PMQ.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/test_http_rest_server.o: test/test_http_rest_server.cpp.o

.PHONY : test/test_http_rest_server.o

# target to build an object file
test/test_http_rest_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_http_rest_server.dir/build.make CMakeFiles/test_http_rest_server.dir/test/test_http_rest_server.cpp.o
.PHONY : test/test_http_rest_server.cpp.o

test/test_http_rest_server.i: test/test_http_rest_server.cpp.i

.PHONY : test/test_http_rest_server.i

# target to preprocess a source file
test/test_http_rest_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_http_rest_server.dir/build.make CMakeFiles/test_http_rest_server.dir/test/test_http_rest_server.cpp.i
.PHONY : test/test_http_rest_server.cpp.i

test/test_http_rest_server.s: test/test_http_rest_server.cpp.s

.PHONY : test/test_http_rest_server.s

# target to generate assembly for a file
test/test_http_rest_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_http_rest_server.dir/build.make CMakeFiles/test_http_rest_server.dir/test/test_http_rest_server.cpp.s
.PHONY : test/test_http_rest_server.cpp.s

test/test_login_factory.o: test/test_login_factory.cpp.o

.PHONY : test/test_login_factory.o

# target to build an object file
test/test_login_factory.cpp.o:
	$(MAKE) -f CMakeFiles/test_login_factory.dir/build.make CMakeFiles/test_login_factory.dir/test/test_login_factory.cpp.o
.PHONY : test/test_login_factory.cpp.o

test/test_login_factory.i: test/test_login_factory.cpp.i

.PHONY : test/test_login_factory.i

# target to preprocess a source file
test/test_login_factory.cpp.i:
	$(MAKE) -f CMakeFiles/test_login_factory.dir/build.make CMakeFiles/test_login_factory.dir/test/test_login_factory.cpp.i
.PHONY : test/test_login_factory.cpp.i

test/test_login_factory.s: test/test_login_factory.cpp.s

.PHONY : test/test_login_factory.s

# target to generate assembly for a file
test/test_login_factory.cpp.s:
	$(MAKE) -f CMakeFiles/test_login_factory.dir/build.make CMakeFiles/test_login_factory.dir/test/test_login_factory.cpp.s
.PHONY : test/test_login_factory.cpp.s

test/test_login_handler.o: test/test_login_handler.cpp.o

.PHONY : test/test_login_handler.o

# target to build an object file
test/test_login_handler.cpp.o:
	$(MAKE) -f CMakeFiles/test_login_handler.dir/build.make CMakeFiles/test_login_handler.dir/test/test_login_handler.cpp.o
.PHONY : test/test_login_handler.cpp.o

test/test_login_handler.i: test/test_login_handler.cpp.i

.PHONY : test/test_login_handler.i

# target to preprocess a source file
test/test_login_handler.cpp.i:
	$(MAKE) -f CMakeFiles/test_login_handler.dir/build.make CMakeFiles/test_login_handler.dir/test/test_login_handler.cpp.i
.PHONY : test/test_login_handler.cpp.i

test/test_login_handler.s: test/test_login_handler.cpp.s

.PHONY : test/test_login_handler.s

# target to generate assembly for a file
test/test_login_handler.cpp.s:
	$(MAKE) -f CMakeFiles/test_login_handler.dir/build.make CMakeFiles/test_login_handler.dir/test/test_login_handler.cpp.s
.PHONY : test/test_login_handler.cpp.s

test/test_server.o: test/test_server.cpp.o

.PHONY : test/test_server.o

# target to build an object file
test/test_server.cpp.o:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/test/test_server.cpp.o
.PHONY : test/test_server.cpp.o

test/test_server.i: test/test_server.cpp.i

.PHONY : test/test_server.i

# target to preprocess a source file
test/test_server.cpp.i:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/test/test_server.cpp.i
.PHONY : test/test_server.cpp.i

test/test_server.s: test/test_server.cpp.s

.PHONY : test/test_server.s

# target to generate assembly for a file
test/test_server.cpp.s:
	$(MAKE) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/test/test_server.cpp.s
.PHONY : test/test_server.cpp.s

test/test_subscriber_container.o: test/test_subscriber_container.cpp.o

.PHONY : test/test_subscriber_container.o

# target to build an object file
test/test_subscriber_container.cpp.o:
	$(MAKE) -f CMakeFiles/test_subscriber_container.dir/build.make CMakeFiles/test_subscriber_container.dir/test/test_subscriber_container.cpp.o
.PHONY : test/test_subscriber_container.cpp.o

test/test_subscriber_container.i: test/test_subscriber_container.cpp.i

.PHONY : test/test_subscriber_container.i

# target to preprocess a source file
test/test_subscriber_container.cpp.i:
	$(MAKE) -f CMakeFiles/test_subscriber_container.dir/build.make CMakeFiles/test_subscriber_container.dir/test/test_subscriber_container.cpp.i
.PHONY : test/test_subscriber_container.cpp.i

test/test_subscriber_container.s: test/test_subscriber_container.cpp.s

.PHONY : test/test_subscriber_container.s

# target to generate assembly for a file
test/test_subscriber_container.cpp.s:
	$(MAKE) -f CMakeFiles/test_subscriber_container.dir/build.make CMakeFiles/test_subscriber_container.dir/test/test_subscriber_container.cpp.s
.PHONY : test/test_subscriber_container.cpp.s

test/test_utf8.o: test/test_utf8.cpp.o

.PHONY : test/test_utf8.o

# target to build an object file
test/test_utf8.cpp.o:
	$(MAKE) -f CMakeFiles/test_utf8.dir/build.make CMakeFiles/test_utf8.dir/test/test_utf8.cpp.o
.PHONY : test/test_utf8.cpp.o

test/test_utf8.i: test/test_utf8.cpp.i

.PHONY : test/test_utf8.i

# target to preprocess a source file
test/test_utf8.cpp.i:
	$(MAKE) -f CMakeFiles/test_utf8.dir/build.make CMakeFiles/test_utf8.dir/test/test_utf8.cpp.i
.PHONY : test/test_utf8.cpp.i

test/test_utf8.s: test/test_utf8.cpp.s

.PHONY : test/test_utf8.s

# target to generate assembly for a file
test/test_utf8.cpp.s:
	$(MAKE) -f CMakeFiles/test_utf8.dir/build.make CMakeFiles/test_utf8.dir/test/test_utf8.cpp.s
.PHONY : test/test_utf8.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... test_server"
	@echo "... test_utf8"
	@echo "... install/local"
	@echo "... test_login_handler"
	@echo "... test_http_rest_server"
	@echo "... test_subscriber_container"
	@echo "... test_login_factory"
	@echo "... install/strip"
	@echo "... pmqttclient"
	@echo "... package"
	@echo "... PMQ"
	@echo "... pmq_obj_lib"
	@echo "... pmqtt"
	@echo "... client/messenger.o"
	@echo "... client/messenger.i"
	@echo "... client/messenger.s"
	@echo "... lib/container/subscriber.o"
	@echo "... lib/container/subscriber.i"
	@echo "... lib/container/subscriber.s"
	@echo "... lib/container/subscriber_container.o"
	@echo "... lib/container/subscriber_container.i"
	@echo "... lib/container/subscriber_container.s"
	@echo "... lib/container/subscriber_node.o"
	@echo "... lib/container/subscriber_node.i"
	@echo "... lib/container/subscriber_node.s"
	@echo "... lib/detail/string.o"
	@echo "... lib/detail/string.i"
	@echo "... lib/detail/string.s"
	@echo "... lib/mqtt/message.o"
	@echo "... lib/mqtt/message.i"
	@echo "... lib/mqtt/message.s"
	@echo "... lib/mqtt/mqtt_connect.o"
	@echo "... lib/mqtt/mqtt_connect.i"
	@echo "... lib/mqtt/mqtt_connect.s"
	@echo "... lib/mqtt/mqtt_message.o"
	@echo "... lib/mqtt/mqtt_message.i"
	@echo "... lib/mqtt/mqtt_message.s"
	@echo "... lib/mqtt/mqtt_message_processor.o"
	@echo "... lib/mqtt/mqtt_message_processor.i"
	@echo "... lib/mqtt/mqtt_message_processor.s"
	@echo "... lib/mqtt/mqtt_package.o"
	@echo "... lib/mqtt/mqtt_package.i"
	@echo "... lib/mqtt/mqtt_package.s"
	@echo "... lib/mqtt/mqtt_publish.o"
	@echo "... lib/mqtt/mqtt_publish.i"
	@echo "... lib/mqtt/mqtt_publish.s"
	@echo "... lib/mqtt/mqtt_subscribe.o"
	@echo "... lib/mqtt/mqtt_subscribe.i"
	@echo "... lib/mqtt/mqtt_subscribe.s"
	@echo "... lib/mqtt/mqtt_types.o"
	@echo "... lib/mqtt/mqtt_types.i"
	@echo "... lib/mqtt/mqtt_types.s"
	@echo "... lib/network/ssl_client_factory.o"
	@echo "... lib/network/ssl_client_factory.i"
	@echo "... lib/network/ssl_client_factory.s"
	@echo "... lib/network/tcp_client_factory.o"
	@echo "... lib/network/tcp_client_factory.i"
	@echo "... lib/network/tcp_client_factory.s"
	@echo "... lib/qos/qos_handler_factory.o"
	@echo "... lib/qos/qos_handler_factory.i"
	@echo "... lib/qos/qos_handler_factory.s"
	@echo "... lib/qos/qos_one_handler.o"
	@echo "... lib/qos/qos_one_handler.i"
	@echo "... lib/qos/qos_one_handler.s"
	@echo "... lib/qos/qos_two_handler.o"
	@echo "... lib/qos/qos_two_handler.i"
	@echo "... lib/qos/qos_two_handler.s"
	@echo "... lib/qos/qos_zero_handler.o"
	@echo "... lib/qos/qos_zero_handler.i"
	@echo "... lib/qos/qos_zero_handler.s"
	@echo "... lib/rest/http_rest_server.o"
	@echo "... lib/rest/http_rest_server.i"
	@echo "... lib/rest/http_rest_server.s"
	@echo "... lib/rest/route_handler.o"
	@echo "... lib/rest/route_handler.i"
	@echo "... lib/rest/route_handler.s"
	@echo "... lib/server/client_handler.o"
	@echo "... lib/server/client_handler.i"
	@echo "... lib/server/client_handler.s"
	@echo "... lib/server/login/login_allow_anonymous_handler.o"
	@echo "... lib/server/login/login_allow_anonymous_handler.i"
	@echo "... lib/server/login/login_allow_anonymous_handler.s"
	@echo "... lib/server/login/login_factory.o"
	@echo "... lib/server/login/login_factory.i"
	@echo "... lib/server/login/login_factory.s"
	@echo "... lib/server/login/login_handler.o"
	@echo "... lib/server/login/login_handler.i"
	@echo "... lib/server/login/login_handler.s"
	@echo "... lib/server/server.o"
	@echo "... lib/server/server.i"
	@echo "... lib/server/server.s"
	@echo "... lib/server/startup_configuration.o"
	@echo "... lib/server/startup_configuration.i"
	@echo "... lib/server/startup_configuration.s"
	@echo "... lib/storage/in_memory_storage.o"
	@echo "... lib/storage/in_memory_storage.i"
	@echo "... lib/storage/in_memory_storage.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/test_http_rest_server.o"
	@echo "... test/test_http_rest_server.i"
	@echo "... test/test_http_rest_server.s"
	@echo "... test/test_login_factory.o"
	@echo "... test/test_login_factory.i"
	@echo "... test/test_login_factory.s"
	@echo "... test/test_login_handler.o"
	@echo "... test/test_login_handler.i"
	@echo "... test/test_login_handler.s"
	@echo "... test/test_server.o"
	@echo "... test/test_server.i"
	@echo "... test/test_server.s"
	@echo "... test/test_subscriber_container.o"
	@echo "... test/test_subscriber_container.i"
	@echo "... test/test_subscriber_container.s"
	@echo "... test/test_utf8.o"
	@echo "... test/test_utf8.i"
	@echo "... test/test_utf8.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

