name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Update system
      run: sudo apt-get update
    - name: Install Dependenicies
      run: sudo apt-get install libyaml-cpp-dev libssl-dev libboost-all-dev cmake
    - name: Install cpprestsdk
      run: mkdir third_party && cd third_party  && git clone https://github.com/microsoft/cpprestsdk.git  && cd third_party/cpprestsdk  && git submodule update --init   && cmake . && make -j4  && make install && cd .. && cd ..
    - uses: actions/checkout@v1
    - name: build makefile
      run: cmake .
    - name: compile
      run: make
      
     
