name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Update system
      run: sudo apt-get update
    - name: Remove gcc g++
      run: apt-get uninstall gcc g++
    - name: Install g++
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install gcc-8 g++-8
    - name: Install Dependenicies
      run: sudo apt-get install libyaml-cpp-dev libssl-dev libboost-all-dev cmake g++
    - name: Install cpprestsdk
      run: sudo apt-get install libcpprest-dev
    - name: g++ Version
      run: g++ -v
    - uses: actions/checkout@v1
    - name: build makefile
      run: cmake . -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake
    - name: compile
      run: make
      
     
