name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo sh install-deps.sh
    - name: build makefile
      run: cmake . 
    - name: compile
      run: make
    - name: Run test
      run: sh run_test.sh   
      
     
